CESNET/perun-ansible

- .gitignore
- group_vars/perun-servers.yml
- roles/apache-perun/templates/perun-ssl.conf.j2
- roles/configuration-perun/templates/perun_properties.j2
- roles/tomcat-perun/templates/server.xml.j2
- roles/tomcat-perun/templates/tomcat7.j2
- Added .gitignore file.
- Source format of perun-ssl.conf
- Renamed apache error log file from specific instance name (copy/pasted)
to generic error.log
> Added our standard .gitignore file, updated apache config

- README.md
- group_vars/perun-servers.yml
- roles/build-perun/tasks/Debian.yml
matches the version used in Perun - update was needed to support correct statement metadata
> updated Oracle drivers requirement to 12.2.0.1.0

- README.md
- ansible.cfg
- roles/perun/tasks/Debian.yml
- fixes in documentation (tomcat8 does not need access to Apache private key, slave scripts are not for server)
- removed sudo for perun group, it creates a security hole
> Fixes deb 9

- roles/apache-perun/templates/perun-ssl.conf.j2
- roles/apache-perun/vars/main.yml
- roles/tomcat-perun/templates/server.xml.j2
- enabled mode proxy_http for apache2
- change in perun-ssl.conf for deploy to tomcat
- added remote deployment of Perun in server.xml
> Change in deploy of apache and tomcat

- README.md
- roles/perun/tasks/Debian.yml
- roles/perun/tasks/Debian_8.yml
- roles/perun/tasks/Debian_9.yml
- roles/perun/tasks/main.yml
- roles/perun/tasks/shibboleth.yml
- roles/perun/vars/main.yml
Replaced Debian version of Shibboleth with SWITCH version. 
Also added modifications of shibboleth2.xml file, and generating of SP private key and certificate.
> Shibboleth installation from SWITCH repository

- group_vars/perun-servers.yml
- roles/shibboleth-perun/tasks/main.yml
- site.yml
- added 3 config items to group_vars/perun-servers.yml - shibboleth_sp_entityID, shibboleth_idp_entityID, shibboleth_idp_metadata_url
- modified perun-shibboleth/tasks/main.yml to use the new config items in setting everything that needs to be configured in shibboleth2.xml
> completed shibboleth config

- roles/shibboleth-perun/handlers/main.yml
- roles/shibboleth-perun/tasks/main.yml
- shibd service is restarted if anything changes in the Shibboleth configuration
> added handler for restart of shibd daemon

- roles/postgre-perun/handlers/main.yml
- roles/postgre-perun/tasks/Debian.yml
- made postgre-perun task idempotent (can be run multiple times without changes)
- added task to edit postgresql.conf and set max_connection=150 to match setting in Perun
> changed max number of postgres connections to match setting in Perun

- group_vars/perun-servers.yml
- roles/unattended-upgrades/tasks/Debian.yml
- roles/unattended-upgrades/tasks/main.yml
- site.yml
Added role that installs package unattended-upgrades that once a day upgrades OS packages. It also installs sendmail so that emails with errors can be delivered.
> added role unattended-upgrades

- roles/configuration-perun/templates/perun_web_gui_properties.j2
- User profile now requires different way of setting user
attributes to show (instead of hide).
> Added new properties to perun-web-gui.properties

- roles/apache-perun/tasks/Debian_9.yml
- roles/work-env/tasks/Debian_9.yml
- roles/work-env/tasks/main.yml
- roles/yubikey/tasks/Yubikey.yml
- site.yml
Moved tasks which set sensible working environment 
- full vim instead of vim-tiny
-  vim in xterm that can copy and paste using mouse
- prompt cointaining FQDN of host
- host and pwd in the title of xterm/gnome-terminal
- installed htop
> added role for setting working environment

- roles/security/templates/rules.j2
added rules to drop invalid packets and packets pretending to be from local addresses but coming from outside interface
> hardened firewall rules to prevent some attacks

- host_vars/perun.example.com/vars.yml
- roles/build-perun/tasks/Debian.yml
- roles/engine-perun/tasks/Debian.yml
- roles/ldap-perun/vars/main.yml
- removed version for jar names
- made installation of Oracle drivers optional
> changes for versioned Perun

- README.md
also added item about the convenience of symbolic links to certificates
> changed README to reflect that Oracle drivers are now optional

- roles/security/tasks/Debian.yml
fixed the condition when fail2ban is stopped
> fail2ban should be stopped if iptables rules are being reloaded

- roles/perun/vars/main.yml
curl is needed for some services
> added curl

- roles/configuration-perun/templates/perun_web_gui_properties.j2
- Allow to set custom name and/or description (including native).
> Updated template for user profile attributes in perun-web-gui.properties

- roles/apache-perun/templates/perun-ssl.conf.j2
- roles/shibboleth-perun/tasks/main.yml
- Fixed redirect of profile, publications and affiliations apps.
- Added new default attributes to attribute-map.xml for Shibboleth.
> Fixed Apache and Shibboleth configs

- roles/configuration-perun/templates/perun_properties.j2
- Added alternative password manager option
- Fixed value of re-captcha private key
> Fixed perun.properties

- roles/configuration-perun/templates/perun_notification_properties.j2
- It was never used and will be removed from sources in 3.6.2
> Removed now unused properties for jabber notifications

- roles/configuration-perun/templates/logback_engine_xml.j2
- roles/configuration-perun/templates/logback_xml.j2
- roles/ldap-perun/templates/logback_ldapc_xml.j2
* Ported some optimizations based on changes in CESNET/perun#2596.
> Optimized logging based on changes in logback-default.xml

- roles/configuration-perun/templates/perun_properties.j2
- We can specify attributes by which we search users/members.
> Added new configuration property in perun.properties
