CESNET/perun-ansible

roles/apache-perun/templates/perun-ssl.conf.j2

- removed KeepAlive off which makes inefficient HTTP
- removed SSL settings that belong and are already set in mods-enabled/mod_ssl.conf
- fixed HSTS header format

removed unnecessary Apache directives

---

roles/configuration-perun/tasks/main.yml

re-enabled access for "others" to /etc/perun/ssl directory

fixed LDAP cert problem

---

roles/engine-perun/tasks/Debian.yml
roles/engine-perun/vars/main.yml
roles/ldap-perun/tasks/install-ldapc-Debian.yml
roles/ldap-perun/vars/main.yml

This commit will copy perun-ldapc init.d script from perun-utils.
It changes copying of perun-engine init.d script as well.
It also deletes unnecessary comments in perun-engine role.

Copy perun-engine/ldapc init.d scripts from perun-utils

---

roles/perun/tasks/main.yml
roles/postgre-perun/tasks/Debian.yml
site.yml

- moved checks for Debian and Ansible versions to site.yml for failing fast
- fixed "when" option of task for creating users in PostgreSQL database

small fixes and improvements

---

roles/engine-perun/tasks/Debian.yml
roles/ldap-perun/tasks/install-ldapc-Debian.yml

modified tasks that start start the services to also set them as enabled after reboot

set services perun-ldapc and perun-engine to start after reboot 

---

roles/apache-perun/tasks/Debian.yml
roles/apache-perun/tasks/Debian_9.yml
roles/apache-perun/tasks/main.yml
roles/apache-perun/vars/main.yml
roles/ldap-perun/tasks/install-ldap-Debian.yml
roles/shibboleth-perun/tasks/main.yml

- added user perun to group ssl-cert (and removed setting perun as owner of private key)
- fixed following symlinks when chmod for cert and key (needed for cert and key generated by certbot)
- added setup of TLS for Debian 9 (it is specific for versions of Apache and OpenSSL)
- added flushing handlers to restart servers at ends of shibboleth-perun and apache-perun
- fixed CLI prompt
- fixed LDAP TLS settings

Better apache config

---

roles/ldap-perun/vars/main.yml

the scripts are no longer needed, they were replaced by /etc/init.d/perun-ldapc script

removed start-ldapc.sh and stop-ldapc.sh scripts

---

roles/unattended-upgrades/tasks/Debian.yml

After updating /etc/aliases, command newaliases needs to be run.

fixed unattended-upgrades to run newaliases

---

roles/apache-perun/templates/perun-ssl.conf.j2
roles/apache-perun/templates/perun.conf.j2
roles/perun/vars/main.yml
roles/security/tasks/Debian.yml
roles/security/tasks/main.yml
roles/security/templates/rules.j2
roles/work-env/tasks/Debian_9.yml
site.yml

- added new role "security" 
- the role installs package fail2ban which prevents DOS attacks
- the role sets up firewall opened for following protocols: ssh, http, https, ldaps and postgresql 
- removed unnecessary logging from Apache config

Fixes for idm test

---

roles/ldap-perun/tasks/install-ldap-Debian.yml

To keep schema in sync with perun repository, constants in Ansible were replaced with loading files from perun-utils.

changed LDAP schema setup to use LDIF files from perun-utils

---

roles/apache-perun/templates/perun-ssl.conf.j2

- By default apache encode query string on rewrite. It causes problems to workflow
"Registrar -> IC -> Registrar" where last returning URL is missing params, since ? and & are
URL encoded.

Do not encode query string when rewriting /*/ic/ to /*-ic/ic/

---

roles/apache-perun/templates/perun-ssl.conf.j2

- By default, Spring Security adds two more security headers.
We can use them in our Apache config. One stop browsers from guessing
content type from its source (and sometimes execute it) and
second allow browsers to detect XSS and block it if detected.
- We want to disable browser caching of HTML and RPC resources
so when we deploy new version, its always loaded from the server.
- We restrict adding header to our apps so other custom apps
on the server are not affected.

Added security and no-cache HTTP headers to default Apache config

---

roles/security/tasks/main.yml
roles/unattended-upgrades/tasks/main.yml
roles/yubikey/tasks/main.yml
site.yml

Check only needed variables for roles security, yubikey, unattended-upgrades and work-env. These roles can be used on non-Perun machines, so they do not need the full set of settings.

check only needed variables for roles

---

roles/engine-perun/tasks/Debian.yml

- We already deployed lib/ for engine purpose, but its handy
to have also matching CLI tools deployed in bin/ so we can
configure new instance more easily.

Deploy also CLI tools to /opt/perun-cli/bin/

---

roles/engine-perun/tasks/Debian.yml

Command task does not do globbing,  it uses its arguments literally, shell task must be used instead.

fixed copying CLI commands

---

roles/configuration-perun/templates/perun_web_gui_properties.j2
roles/wui-perun/tasks/main.yml
roles/wui-perun/vars/main.yml

- We will use central CESNET repository.
- We use version-less folders (since we started versioning WUI).
- Each webapp is now own ansible idempotent task.
- Updated comment in perun-web-gui.properties

New way of Perun-WUI deployment

---

roles/configuration-perun/templates/perun_engine.j2

- Debian 9 / Perl 5.24.1 doesn't include current folder to perl
libs, so we must define it explicitly so gen/send scripts
see necessary libraries.

Include current folder to perl libs for engine

---

roles/configuration-perun/templates/perun_properties.j2
roles/configuration-perun/templates/perun_web_gui_properties.j2

- Added new properties, which are by default disabled or configured,
but it might be handy to change them in a config for specific
Perun instance.
- Changed validation window for password reset and mail change
to 24 hours.

Updated template of perun.properties and perun-web-gui.properties

---

roles/yubikey/tasks/Yubikey.yml

- makes sure that ~/.ssh/ and ~/.ssh/authorized_keys belong to group of the user

ensured correct groups on ssh keys

---

host_vars/perun.example.com/vars.yml
roles/apache-perun/tasks/Debian.yml
roles/ldap-perun/templates/perun_ldapc_properties.j2

- added option slapd_password_sasl_login_namespace for SASL login Kerberos namespace
- also made IGTF certificates optional, when apache_ca_certificate_path is not defined, the installation is skipped

added option for SASL login namespace

---

group_vars/all/vars.yml
roles/configuration-perun/templates/jdbc_properties.j2

- If we merge HikariCP, we might want to tweak number of allowed
DB connections on each instance, but we will generally use
our default (we set postgres to 150).

Support customization of HikariCP properties through our jdbc.properties

---

roles/postgre-perun/tasks/Debian.yml

Single quotes inside double quotes do not require char escaping. Using `\` as the escaping char makes the resulting YAML invalid.

FIX postgre-perun: Fix invalid escaping of quotes

---

roles/configuration-perun/templates/perun_registrar_lib.j2

- We now allow setting custom SMTP server config for registrar.
Values presented in a file are default (sending to localhost:25),
since by default installed sendmail handles mails for us.

Added new perun-registrar properties

---

roles/configuration-perun/templates/logback_engine_xml.j2

- Unlike any other log file we created perun-engine log files
explicitly with day and count number omitting presence of the
base file perun-engine.log.
- This is now fixed. Current log file is always perun-engine.log
and rotated files are perun-engine.log.[YYYY-MM-DD].[counter].

Logging file perun-engine.log was missing in logback config

---

group_vars/all/vars.yml
roles/configuration-perun/templates/jdbc_properties.j2
roles/configuration-perun/templates/perun_notification_properties.j2
roles/configuration-perun/templates/perun_properties.j2
roles/configuration-perun/templates/perun_registrar_lib.j2

- Added optional SMTP configuration to perun.properties
- Removed now unused SMTP configuration from perun-registrar.properties
and perun-notification.properties
- Updated jdbc.properties with new options for HikariCP. Default values
are stored in vars.yml.

Updated configuration files to support Perun 3.5.2

---

roles/configuration-perun/templates/perun_properties.j2

- We now allow specifying login-namespaces for which we want to
auto-create necessary attributes in Perun.
- Compatible for 3.5.4+.

Added new optional param to perun.properties

---

roles/configuration-perun/templates/perun_properties.j2

- Filling param with mail will cause Perun to send all RT messages
to such mail address instead of contacting RT API.
- Compatible for 3.5.5+.

Added param perun.rt.sendToMail to perun.properties

---

roles/shibboleth-perun/tasks/Debian.yml

- It is generic attribute which contains external affiliations of user
(with scope not related to the used IdP). This is usually provided
by proxy IdP to the services.
If proxy is before Perun, then is pushes source affiliation
(voPersonExternalAffiliation) in standard affiliation attribute, so it
is stored within proper attribute.
So this attribute is present only when original IdP used by user
is a proxy too. Then "affiliation" contains "affiliate@proxy" and
"voPersonExternalAffiliation" contains other affiliations.

Added voPersonExternalAffiliation

---

roles/ldap-perun/tasks/install-ldapc-Debian.yml
roles/ldap-perun/templates/perun_ldapc.j2
roles/ldap-perun/templates/perun_ldapc_attributes_xml.j2
roles/ldap-perun/vars/main.yml

- This can be merged only after release of Perun 3.8.0 !
- Script files for older LDAPc are now unused and won't be deployed.
- Old LDAPc jars won't be deployed, new with the same name will be used.
- We no longer perform explicit sync after install, it is done
by default by new LDAPc on service start.
- Added required config files with default values (forcing sync on
LDAPc startup).

Support new LDAPc installation

---

roles/configuration-perun/templates/perun_roles_yml.j2

- Perun roles are now listed under the key perun_roles.
- Template now also contains key perun_policies with default policy which
will be used later.

perun_roles template change

---

roles/configuration-perun/templates/perun_engine.j2

- There is no reason to create new cookie for each propagation start
in perun-engine (new process id). Engine can keep own cookie
stored in a single file.

Keep single cookie for perun-engine

---

roles/apache-perun/templates/perun-ssl.conf.j2

- We must allow google.com and gstatic.com in script-src and frame-src
in order to support ReCAPTCHA on /non/ authz password reset or registration.

Fixed loading of ReCAPTCHA in Perun

---

roles/postgres-perun/tasks/Debian.yml

- Initialization was moved to db init script and is part of
"Create tables" task.
- Merge only after 3.9.0 release.

Removed "create initial user" task form postgres-perun

---

roles/configuration-perun/templates/logback_xml.j2
roles/perun/tasks/Debian.yml

- All perun-core logging for group synchronization threads
will be redirected by using SIFT appender.

Support logging of groups synchronizations in separate files

---

roles/configuration-perun/templates/perun_properties.j2
roles/configuration-perun/templates/perun_web_gui_properties.j2

- At EduTEAMS they need more strict rules for group naming.
- Added secondary regex config in perun.properties.
- Added secondary regex config in perun-web-gui.properties

Added new config properties to limit group name for eduteams
